### ISSUE TITLE
Prototype webservices to perform CRUD operations on the DB

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.persistence#4]
- [x] Decide final word on which component will host the webservices, see [here](https://www.lucidchart.com/documents/edit/4666b850-512b-5184-8a79-20de0a000fde/1)
- [x] Investigate if there is any framework to generate the webservices for us?
- [x] Create/generate a webservice to retrieve all simulations for a given user
- [x] Create simple html page that calls the webservice and writes the names of the existing simulations

**Comment by gidili** [comment]
@tarelli @ddanny is the idea for this to be another OSGi service same as the ones we have in one of the bundles plus some layer to expose the webservice calls (restlet kind of stuff) so that we can call it straight from the clientside code (straight up or via wrapping it in the Geppetto javascript API)?

**Comment by tarelli** [comment]
@gidili yes, the second item of the list is a technological investigation to figure out what's the best way to do this.

**Comment by gidili** [comment]
@tarelli @ddanny given what the db schema looks like, I doubt there is a solution that could generate a CRUD ws that does exactly what we want it to do in a clean way, but interesting to look into it nonetheless. 

The solution might end up being generating some stuff automatically like that and having a manually coded layer on top to expose exactly what we want to expose and converting json objects to our exact object model. This would also help decouple the object model from the ws interfaces so that if something changes in the future in the object model we have wiggle room to wire things up the way we want.

**Comment by ddanny** [comment]
I doubt we will find the perfect framework to generate the webservices for us, but I may not understand the requirements entirely.

On the other side, restlet seems to have OSGi support and can be integrated with Virgo, so we could probably use it: http://eclipse.dzone.com/articles/restlet-and-osgi-remote

**Comment by tarelli** [comment]
I was looking at that combination myself, looks like it's a good candidate to try out.
